[build-system]
requires = ["scikit-build-core", "boutdata", "jinja2"]
build-backend = "scikit_build_core.build"

[project]
name = "hermes-3"
version = "1.5.0"

[dependency-groups]
dev = [
     "cmake~=4.2",
     "clang-format~=22.0",
     "clang-tidy~=22.0",
     "clangd~=22.0",
     "clangd-tidy~=1.1",
     "cmakelang~=0.6",
     "prek>=0.3.5",
     "pyyaml~=6.0",
     "ruff~=0.15",
     "sphinx-lint~=1.0",
     "sync-with-uv~=0.5.0",
]

[tool.uv.workspace]

[tool.scikit-build]
cmake.version = ">=3.25"
cmake.build-type = "Release"
wheel.packages = []
#wheel.install-dir = "${SKBUILD_DATA_DIR}"
sdist.exclude = ["*"]
sdist.include = ["/README.md", "/LICENSE", "/pyproject.toml", "/src/*.cxx", "/include/*.hxx*", "/hermes-3.cxx", "/hermes-3.hxx",
                 "/CMakeLists.txt", "cmake/**.cmake*",
                 "/json_database", "external/BOUT-dev/README.md", "external/BOUT-dev/LICENSE", "external/BOUT-dev/LICENSE.GPL", "external/BOUT-dev/CMakeLists.txt", "external/BOUT-dev/bout++Config.cmake.in", "external/BOUT-dev/cmake_build_defines.hxx.in", "external/BOUT-dev/cmake/*.cmake*", "external/BOUT-dev/bin/bout-config.in", "external/BOUT-dev/tools/pylib/boutconfig/__init__.py.cin", "external/BOUT-dev/src/**/*.cxx", "external/BOUT-dev/src/**/*.hxx",
                 "external/BOUT-dev/include/bout/**/*.h*", "external/BOUT-dev/externalpackages/cpptrace", "external/BOUT-dev/externalpackages/fmt", "external/BOUT-dev/externalpackages/mpark.variant", "external/BOUT-dev/externalpackages/PVODE", "!external/BOUT-dev/externalpackages/PVODE/source/build-aux", "!external/BOUT-dev/externalpackages/PVODE/precon/build-aux", "!*~", "external/BOUT-dev/src/field/gen_fieldops.jinja", "external/BOUT-dev/src/field/gen_fieldops.py", "external/BOUT-dev/locale", "external/json.hxx"]

[tool.scikit-build.cmake.define]
BUILD_SHARED_LIBS = false
BOUT_ENABLE_PYTHON = "OFF"
HERMES_TESTS = false
BOUT_BUILD_EXAMPLES = false
