#!/usr/bin/env python3

import pathlib
import os
import itertools
import argparse

from boututils.run_wrapper import launch

EXAMPLES_DEFAULT = pathlib.Path("../../../examples")
HERMES_3_DEFAULT = pathlib.Path("../../../hermes-3")

NPROCS = {"tokamak-2D": 12, "tokamak-3D": 12}


def run_examples(examples_dir: pathlib.Path, hermes3_exe: pathlib.Path, verbose: bool):
    # Specify the number of processors needed by each category of test. If
    # not specified, assume 1.

    failed_tests = []

    for category, examples in itertools.groupby(
        sorted(examples_dir.rglob("*.inp")), lambda p: p.parent.parent
    ):
        category_name = str(category.relative_to(examples_dir))
        print(f"\033[1mRunning tests in category '{category_name}'.\033[0m")
        print(f"Working directory: {category}")
        os.chdir(category)
        for example in examples:
            example_dir = example.parent
            print(f"Running {example_dir.relative_to(examples_dir)}...")
            s, out = launch(
                f"{hermes3_exe} -d {example_dir} nout=1 timestep=1e-3 input:error_on_unused_options=true",
                nproc=NPROCS.get(category_name, 1),
                mthread=1,
                pipe=True,
            )
            if s == 0:
                print("\t\033[92mPASSED!\033[0m")
            else:
                print("\t\033[91mFAILED!\033[0m")
                if verbose:
                    print(out)
                failed_tests.append(example_dir)
        print()

    print("-" * 80, end="\n\n")
    nfailed = len(failed_tests)
    if nfailed == 0:
        print("\033[92mSUCCESS: All examples were able to start running.\033[0m")
        exit(0)
    else:
        print(f"\033[91mFAILURE: The following {nfailed} examples failed to run")
        print("\t", end="")
        print("\n\t".join(map(str, failed_tests)))
        print("\033[0m")
        exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--example-dir", default=EXAMPLES_DEFAULT, type=pathlib.Path)
    parser.add_argument("--hermes-exe", default=HERMES_3_DEFAULT, type=pathlib.Path)
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()
    run_examples(args.example_dir.resolve(), args.hermes_exe.resolve(), args.verbose)
